### ISSUE TITLE
Doesn't work when run as the root user

### ISSUE THREAD

**Issue by mattvw** [CodyKank/pyupdate#7]
I run into issues when I try to run this as the root user. It appears it assumes that you are running this as a normal user (and need to become root), which won't always be the case.

When running this as the root user, I get this output:

```
[root@<host> pyupdate]# python36 python_update.py 
Welcome root
The last update was: This is the first update!. 
Would you like to update now? [y/n]: y
System identified as, or based on: rhel
Proceeding to update system. . .
su: invalid option -- 'y'

Usage:
 su [options] [-] [USER [arg]...]

Change the effective user id and group id to that of USER.
A mere - implies -l.   If USER not given, assume root.

Options:
 -m, -p, --preserve-environment  do not reset environment variables
 -g, --group <group>             specify the primary group
 -G, --supp-group <group>        specify a supplemental group

 -, -l, --login                  make the shell a login shell
 -c, --command <command>         pass a single command to the shell with -c
 --session-command <command>     pass a single command to the shell with -c
                                 and do not create a new session
 -f, --fast                      pass -f to the shell (for csh or tcsh)
 -s, --shell <shell>             run shell if /etc/shells allows it

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see su(1).
Traceback (most recent call last):
  File "python_update.py", line 268, in <module>
    main()
  File "python_update.py", line 26, in main
    update(user)
  File "python_update.py", line 91, in update
    save_update(user_name)
  File "python_update.py", line 159, in save_update
    file_ob = open(update_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/.previous-update.txt'
```

There appear to be a couple issues here: (1) It is running the 'su' command without checking to see if the user is already the root user, and therefore, running su/sudo can/should be skipped in this case and (2) the script is assuming the user's home directory is always going to be at /home/<username>, which obviously won't work for root and may not always be correct. Sure, /home is the default location for normal users probably for all Linux distros, it's still probably not a great idea to hard-code this since it's always going to ultimately be up to the user where they want their home directory to be located, and certainly the root user's home directory is always going to be /root.

For (1), this should be pretty easy to fix (which I say without knowing Python...). You're already figuring out the username of the user running the script. It should be fairly straightforward to add a check that if it's the root user, then skip running su and/or sudo with the update command.

For (2), I would recommend using the user's already set $HOME environment variable instead of hard-coding the home directory location to be under /home. Using the $HOME env. variable will always work, regardless of what user it is (i.e. root or normal user) and where the user decided to put their home directory. I think the $HOME variable is pretty universal across Linux/Unix distros.

This is running on RHEL 7, with the python36 package installed from EPEL.

**Comment by CodyKank** [comment]
Thanks for suggestions. This started out as sort of beginner / first project. I will start to get around fixing these mistakes. Note that your suggestion number 2 was solved with merging #8 .
